import type { Bank } from '@/domain/bank'

/**
 * Ten fictional Saudi-market banks (mock-data-requirements.md — Banks).
 * Names, contacts, and figures are fictional prototype data with no
 * real-brand claims; text monograms only — never real bank branding.
 * Exposure is derived from active deposits (PD-06), never stored here.
 * `BNK-010` is the single inactive bank excluded from new RFQs.
 */
export const banks: readonly Bank[] = [
  {
    id: 'BNK-001',
    code: 'NNB',
    nameAr: 'بنك النخيل الوطني',
    nameEn: 'Al Nakheel National Bank',
    shortName: 'النخيل',
    logoUrl: null,
    monogram: 'نخ',
    relationshipManagerName: 'فهد الرشيدي',
    relationshipManagerEmail: 'fahad.alrashidi@nnb.example.test',
    relationshipManagerPhone: '+966-11-000-1001',
    isActive: true,
    riskCategory: 'LOW',
  },
  {
    id: 'BNK-002',
    code: 'WHB',
    nameAr: 'مصرف الواحة',
    nameEn: 'Al Waha Bank',
    shortName: 'الواحة',
    logoUrl: null,
    monogram: 'وح',
    relationshipManagerName: 'منيرة السبيعي',
    relationshipManagerEmail: 'munira.alsubaie@whb.example.test',
    relationshipManagerPhone: '+966-11-000-1002',
    isActive: true,
    riskCategory: 'LOW',
  },
  {
    id: 'BNK-003',
    code: 'SSB',
    nameAr: 'بنك السدرة السعودي',
    nameEn: 'Sidra Saudi Bank',
    shortName: 'السدرة',
    logoUrl: null,
    monogram: 'سد',
    relationshipManagerName: 'بدر الحارثي',
    relationshipManagerEmail: 'badr.alharthi@ssb.example.test',
    relationshipManagerPhone: '+966-11-000-1003',
    isActive: true,
    riskCategory: 'MEDIUM',
  },
  {
    id: 'BNK-004',
    code: 'MIB',
    nameAr: 'بنك المها للاستثمار',
    nameEn: 'Al Maha Investment Bank',
    shortName: 'المها',
    logoUrl: null,
    monogram: 'مه',
    relationshipManagerName: 'عبير الزهراني',
    relationshipManagerEmail: 'abeer.alzahrani@mib.example.test',
    relationshipManagerPhone: '+966-11-000-1004',
    isActive: true,
    riskCategory: 'MEDIUM',
  },
  {
    id: 'BNK-005',
    code: 'FYB',
    nameAr: 'مصرف الفيحاء',
    nameEn: 'Al Fayhaa Bank',
    shortName: 'الفيحاء',
    logoUrl: null,
    monogram: 'في',
    relationshipManagerName: 'سلطان العمري',
    relationshipManagerEmail: 'sultan.alamri@fyb.example.test',
    relationshipManagerPhone: '+966-11-000-1005',
    isActive: true,
    riskCategory: 'LOW',
  },
  {
    id: 'BNK-006',
    code: 'NFB',
    nameAr: 'بنك الشمال الأول',
    nameEn: 'Northern First Bank',
    shortName: 'الشمال',
    logoUrl: null,
    monogram: 'شم',
    relationshipManagerName: 'نايف الدوسري',
    relationshipManagerEmail: 'naif.aldosari@nfb.example.test',
    relationshipManagerPhone: '+966-11-000-1006',
    isActive: true,
    riskCategory: 'MEDIUM',
  },
  {
    id: 'BNK-007',
    code: 'CCB',
    nameAr: 'بنك الساحل التجاري',
    nameEn: 'Coastal Commercial Bank',
    shortName: 'الساحل',
    logoUrl: null,
    monogram: 'سح',
    relationshipManagerName: 'ريما القحطاني',
    relationshipManagerEmail: 'reema.alqahtani@ccb.example.test',
    relationshipManagerPhone: '+966-12-000-1007',
    isActive: true,
    riskCategory: 'MEDIUM',
  },
  {
    id: 'BNK-008',
    code: 'DRB',
    nameAr: 'مصرف الديرة',
    nameEn: 'Al Deera Bank',
    shortName: 'الديرة',
    logoUrl: null,
    monogram: 'دي',
    relationshipManagerName: 'ماجد الشمري',
    relationshipManagerEmail: 'majed.alshammari@drb.example.test',
    relationshipManagerPhone: '+966-11-000-1008',
    isActive: true,
    riskCategory: 'LOW',
  },
  {
    id: 'BNK-009',
    code: 'RWB',
    nameAr: 'بنك الروابي',
    nameEn: 'Al Rawabi Bank',
    shortName: 'الروابي',
    logoUrl: null,
    monogram: 'رو',
    relationshipManagerName: 'هيفاء العتيق',
    relationshipManagerEmail: 'haifa.alateeq@rwb.example.test',
    relationshipManagerPhone: '+966-13-000-1009',
    isActive: true,
    riskCategory: 'HIGH',
  },
  {
    id: 'BNK-010',
    code: 'SIB',
    nameAr: 'بنك القمة الدولي',
    nameEn: 'Summit International Bank',
    shortName: 'القمة',
    logoUrl: null,
    monogram: 'قم',
    relationshipManagerName: 'تركي المالكي',
    relationshipManagerEmail: 'turki.almalki@sib.example.test',
    relationshipManagerPhone: '+966-11-000-1010',
    isActive: false,
    riskCategory: 'HIGH',
  },
]

/** Banks eligible for new RFQs — inactive banks are excluded centrally. */
export const activeBankIds: readonly string[] = banks
  .filter((bank) => bank.isActive)
  .map((bank) => bank.id)
